name: Staging â€“ Storybook

on:
  workflow_call:
    secrets:
      TURBO_TOKEN:
        required: true
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-build-and-quality:
    name: validate-build-and-quality
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: CI setup
        uses: ./.github/actions/ci-setup
        with:
          include-checkout: true

      - name: CI validate
        uses: ./.github/actions/ci-validate
        with:
          target: storybook

      - name: Build
        run: pnpm turbo run build --filter=@kartuli/storybook
        shell: bash

      - name: Start preview server (background)
        run: |
          pnpm turbo run preview --filter=@kartuli/storybook &
          sleep 15
        shell: bash

      - name: Setup Playwright
        uses: ./.github/actions/ci-setup-playwright

      - name: Run E2E
        env:
          BASE_URL: "http://localhost:6006"
        run: pnpm --filter @kartuli/e2e exec playwright test tests/storybook
        shell: bash

      - name: Upload E2E artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-artifacts-storybook-${{ github.run_number }}
          path: tools/e2e/test-results/
          retention-days: 3
